# Schema reference: https://github.com/openintent/oiml/blob/main/packages/schema/project/index.ts
name: Posty
description: >
  A simple application built on the OpenIntent framework. It manages posts
  with a clean API and modern UI.
version: 0.1.0

api:
  framework: next
  language: typescript

database:
  type: postgres
  framework: prisma
  schema: prisma/schema.prisma
  connection: env:DATABASE_URL

ui:
  framework: next
  language: typescript
  components: shadcn/ui
  base_components:
    - Input: "@/components/ui/input"
    - Button: "@/components/ui/button"
    - Card: "@/components/ui/card"
  theme:
    primary_color: "#3b82f6"
    accent_color: "#10b981"
    border_radius: "0.5rem"

provider:
  name: aws
  region: us-east-1

auth:
  provider: next-auth
  adapter: prisma
  sessionStrategy: jwt

paths:
  api: app/api
  components: app/components
  database: prisma/*
  utils: packages/utils
  types: packages/types

intents:
  directory: ".openintent/intents"
