# Schema reference: https://github.com/openintent/oiml/blob/main/packages/schema/project/index.ts
name: integrator
description: ""
version: 0.1.0
api:
  language: typescript
  framework: next
database:
  type: postgres
  framework: prisma
  schema: prisma/schema.prisma
  connection: env:DATABASE_URL
  autorun_migrations: true
ui:
  framework: next
  components: shadcn/ui
  language: typescript
intents:
  directory: .oiml/intents
paths:
  api: app/api
  components: app/components
  database: prisma/*
  types: types/*
