/**
 * Schema Registration File
 *
 * This file is auto-generated during the build process.
 * It imports and registers all available OIML schema versions.
 *
 * DO NOT EDIT MANUALLY - This file is generated by the build script.
 */

import { registerSchema } from "./schema-loader";

// eslint-disable-next-line @typescript-eslint/no-var-requires
const schema010 = require("packages/schema/schemas/oiml.intent/0.1.0/schema.zod.js");
registerSchema("0.1.0", schema010);

export function registerAllSchemas() {
  // All schemas are registered above
}
