# Schema reference: https://github.com/openintent/oiml/blob/main/packages/schema/project/index.ts
name: TodoApp
description: >
  A simple todo application built on the OIML framework. It manages tasks
  with a clean API and modern UI.
version: 0.1.0

api:
  framework: next
  language: typescript

database:
  type: postgres
  framework: prisma
  schema: prisma/schema.prisma
  connection: env:DATABASE_URL

ui:
  framework: next
  language: typescript
  components: shadcn/ui
  base_components:
    - Input: "@/components/ui/input"
    - Button: "@/components/ui/button"
    - Card: "@/components/ui/card"
  theme:
    primary_color: "#3b82f6"
    accent_color: "#10b981"
    border_radius: "0.5rem"

provider:
  name: aws
  region: us-east-1

auth:
  provider: next-auth
  adapter: prisma
  sessionStrategy: jwt

paths:
  api: app/api
  components: app/components
  database: prisma/*
  utils: packages/utils
  types: packages/types

adapters:
  auth:
    provider: next-auth
    options:
      secret: env:NEXTAUTH_SECRET
  storage:
    provider: s3
    bucket: todoapp-assets
    region: us-east-1

lint:
  eslint: true
  prettier: true

build:
  command: "pnpm build"
  output: ".next"
  framework: next

deploy:
  provider: vercel
  region: iad1
  env: production

policies:
  max_files_changed: 25
  max_loc_added: 500
  forbidden_paths:
    - "node_modules/"
    - ".next/"
    - "dist/"
  reviewers_required: 1
  tests_required: true

intents:
  directory: ".oiml/intents"
  schema_version: 1.0
  default_review_policy: auto

metadata:
  maintainers:
    - name: "TodoApp Team"
      email: "team@todoapp.dev"
  repository: "https://github.com/openintent/todoapp"

