// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"streamify/ent/album"
	"streamify/ent/artist"
	"streamify/ent/predicate"
	"streamify/ent/track"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// AlbumUpdate is the builder for updating Album entities.
type AlbumUpdate struct {
	config
	hooks    []Hook
	mutation *AlbumMutation
}

// Where appends a list predicates to the AlbumUpdate builder.
func (_u *AlbumUpdate) Where(ps ...predicate.Album) *AlbumUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *AlbumUpdate) SetTitle(v string) *AlbumUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *AlbumUpdate) SetNillableTitle(v *string) *AlbumUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetArtistID sets the "artist_id" field.
func (_u *AlbumUpdate) SetArtistID(v uuid.UUID) *AlbumUpdate {
	_u.mutation.SetArtistID(v)
	return _u
}

// SetNillableArtistID sets the "artist_id" field if the given value is not nil.
func (_u *AlbumUpdate) SetNillableArtistID(v *uuid.UUID) *AlbumUpdate {
	if v != nil {
		_u.SetArtistID(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AlbumUpdate) SetCreatedAt(v time.Time) *AlbumUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AlbumUpdate) SetNillableCreatedAt(v *time.Time) *AlbumUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetArtist sets the "artist" edge to the Artist entity.
func (_u *AlbumUpdate) SetArtist(v *Artist) *AlbumUpdate {
	return _u.SetArtistID(v.ID)
}

// AddTrackIDs adds the "tracks" edge to the Track entity by IDs.
func (_u *AlbumUpdate) AddTrackIDs(ids ...uuid.UUID) *AlbumUpdate {
	_u.mutation.AddTrackIDs(ids...)
	return _u
}

// AddTracks adds the "tracks" edges to the Track entity.
func (_u *AlbumUpdate) AddTracks(v ...*Track) *AlbumUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTrackIDs(ids...)
}

// Mutation returns the AlbumMutation object of the builder.
func (_u *AlbumUpdate) Mutation() *AlbumMutation {
	return _u.mutation
}

// ClearArtist clears the "artist" edge to the Artist entity.
func (_u *AlbumUpdate) ClearArtist() *AlbumUpdate {
	_u.mutation.ClearArtist()
	return _u
}

// ClearTracks clears all "tracks" edges to the Track entity.
func (_u *AlbumUpdate) ClearTracks() *AlbumUpdate {
	_u.mutation.ClearTracks()
	return _u
}

// RemoveTrackIDs removes the "tracks" edge to Track entities by IDs.
func (_u *AlbumUpdate) RemoveTrackIDs(ids ...uuid.UUID) *AlbumUpdate {
	_u.mutation.RemoveTrackIDs(ids...)
	return _u
}

// RemoveTracks removes "tracks" edges to Track entities.
func (_u *AlbumUpdate) RemoveTracks(v ...*Track) *AlbumUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTrackIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AlbumUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AlbumUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AlbumUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AlbumUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AlbumUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := album.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Album.title": %w`, err)}
		}
	}
	if _u.mutation.ArtistCleared() && len(_u.mutation.ArtistIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Album.artist"`)
	}
	return nil
}

func (_u *AlbumUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(album.Table, album.Columns, sqlgraph.NewFieldSpec(album.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(album.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(album.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ArtistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   album.ArtistTable,
			Columns: []string{album.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArtistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   album.ArtistTable,
			Columns: []string{album.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TracksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   album.TracksTable,
			Columns: []string{album.TracksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(track.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTracksIDs(); len(nodes) > 0 && !_u.mutation.TracksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   album.TracksTable,
			Columns: []string{album.TracksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(track.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TracksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   album.TracksTable,
			Columns: []string{album.TracksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(track.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{album.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AlbumUpdateOne is the builder for updating a single Album entity.
type AlbumUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AlbumMutation
}

// SetTitle sets the "title" field.
func (_u *AlbumUpdateOne) SetTitle(v string) *AlbumUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *AlbumUpdateOne) SetNillableTitle(v *string) *AlbumUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetArtistID sets the "artist_id" field.
func (_u *AlbumUpdateOne) SetArtistID(v uuid.UUID) *AlbumUpdateOne {
	_u.mutation.SetArtistID(v)
	return _u
}

// SetNillableArtistID sets the "artist_id" field if the given value is not nil.
func (_u *AlbumUpdateOne) SetNillableArtistID(v *uuid.UUID) *AlbumUpdateOne {
	if v != nil {
		_u.SetArtistID(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AlbumUpdateOne) SetCreatedAt(v time.Time) *AlbumUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AlbumUpdateOne) SetNillableCreatedAt(v *time.Time) *AlbumUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetArtist sets the "artist" edge to the Artist entity.
func (_u *AlbumUpdateOne) SetArtist(v *Artist) *AlbumUpdateOne {
	return _u.SetArtistID(v.ID)
}

// AddTrackIDs adds the "tracks" edge to the Track entity by IDs.
func (_u *AlbumUpdateOne) AddTrackIDs(ids ...uuid.UUID) *AlbumUpdateOne {
	_u.mutation.AddTrackIDs(ids...)
	return _u
}

// AddTracks adds the "tracks" edges to the Track entity.
func (_u *AlbumUpdateOne) AddTracks(v ...*Track) *AlbumUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTrackIDs(ids...)
}

// Mutation returns the AlbumMutation object of the builder.
func (_u *AlbumUpdateOne) Mutation() *AlbumMutation {
	return _u.mutation
}

// ClearArtist clears the "artist" edge to the Artist entity.
func (_u *AlbumUpdateOne) ClearArtist() *AlbumUpdateOne {
	_u.mutation.ClearArtist()
	return _u
}

// ClearTracks clears all "tracks" edges to the Track entity.
func (_u *AlbumUpdateOne) ClearTracks() *AlbumUpdateOne {
	_u.mutation.ClearTracks()
	return _u
}

// RemoveTrackIDs removes the "tracks" edge to Track entities by IDs.
func (_u *AlbumUpdateOne) RemoveTrackIDs(ids ...uuid.UUID) *AlbumUpdateOne {
	_u.mutation.RemoveTrackIDs(ids...)
	return _u
}

// RemoveTracks removes "tracks" edges to Track entities.
func (_u *AlbumUpdateOne) RemoveTracks(v ...*Track) *AlbumUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTrackIDs(ids...)
}

// Where appends a list predicates to the AlbumUpdate builder.
func (_u *AlbumUpdateOne) Where(ps ...predicate.Album) *AlbumUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AlbumUpdateOne) Select(field string, fields ...string) *AlbumUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Album entity.
func (_u *AlbumUpdateOne) Save(ctx context.Context) (*Album, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AlbumUpdateOne) SaveX(ctx context.Context) *Album {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AlbumUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AlbumUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AlbumUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := album.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Album.title": %w`, err)}
		}
	}
	if _u.mutation.ArtistCleared() && len(_u.mutation.ArtistIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Album.artist"`)
	}
	return nil
}

func (_u *AlbumUpdateOne) sqlSave(ctx context.Context) (_node *Album, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(album.Table, album.Columns, sqlgraph.NewFieldSpec(album.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Album.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, album.FieldID)
		for _, f := range fields {
			if !album.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != album.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(album.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(album.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ArtistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   album.ArtistTable,
			Columns: []string{album.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ArtistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   album.ArtistTable,
			Columns: []string{album.ArtistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(artist.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TracksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   album.TracksTable,
			Columns: []string{album.TracksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(track.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTracksIDs(); len(nodes) > 0 && !_u.mutation.TracksCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   album.TracksTable,
			Columns: []string{album.TracksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(track.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TracksIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   album.TracksTable,
			Columns: []string{album.TracksColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(track.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Album{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{album.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
