// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"streamify/ent/album"
	"streamify/ent/artist"
	"streamify/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// ArtistUpdate is the builder for updating Artist entities.
type ArtistUpdate struct {
	config
	hooks    []Hook
	mutation *ArtistMutation
}

// Where appends a list predicates to the ArtistUpdate builder.
func (_u *ArtistUpdate) Where(ps ...predicate.Artist) *ArtistUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ArtistUpdate) SetName(v string) *ArtistUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ArtistUpdate) SetNillableName(v *string) *ArtistUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetImageURL sets the "image_url" field.
func (_u *ArtistUpdate) SetImageURL(v string) *ArtistUpdate {
	_u.mutation.SetImageURL(v)
	return _u
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_u *ArtistUpdate) SetNillableImageURL(v *string) *ArtistUpdate {
	if v != nil {
		_u.SetImageURL(*v)
	}
	return _u
}

// ClearImageURL clears the value of the "image_url" field.
func (_u *ArtistUpdate) ClearImageURL() *ArtistUpdate {
	_u.mutation.ClearImageURL()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ArtistUpdate) SetCreatedAt(v time.Time) *ArtistUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ArtistUpdate) SetNillableCreatedAt(v *time.Time) *ArtistUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddAlbumIDs adds the "albums" edge to the Album entity by IDs.
func (_u *ArtistUpdate) AddAlbumIDs(ids ...uuid.UUID) *ArtistUpdate {
	_u.mutation.AddAlbumIDs(ids...)
	return _u
}

// AddAlbums adds the "albums" edges to the Album entity.
func (_u *ArtistUpdate) AddAlbums(v ...*Album) *ArtistUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAlbumIDs(ids...)
}

// Mutation returns the ArtistMutation object of the builder.
func (_u *ArtistUpdate) Mutation() *ArtistMutation {
	return _u.mutation
}

// ClearAlbums clears all "albums" edges to the Album entity.
func (_u *ArtistUpdate) ClearAlbums() *ArtistUpdate {
	_u.mutation.ClearAlbums()
	return _u
}

// RemoveAlbumIDs removes the "albums" edge to Album entities by IDs.
func (_u *ArtistUpdate) RemoveAlbumIDs(ids ...uuid.UUID) *ArtistUpdate {
	_u.mutation.RemoveAlbumIDs(ids...)
	return _u
}

// RemoveAlbums removes "albums" edges to Album entities.
func (_u *ArtistUpdate) RemoveAlbums(v ...*Album) *ArtistUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAlbumIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ArtistUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArtistUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ArtistUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArtistUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArtistUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := artist.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Artist.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ArtistUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(artist.Table, artist.Columns, sqlgraph.NewFieldSpec(artist.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(artist.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageURL(); ok {
		_spec.SetField(artist.FieldImageURL, field.TypeString, value)
	}
	if _u.mutation.ImageURLCleared() {
		_spec.ClearField(artist.FieldImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(artist.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.AlbumsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   artist.AlbumsTable,
			Columns: []string{artist.AlbumsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAlbumsIDs(); len(nodes) > 0 && !_u.mutation.AlbumsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   artist.AlbumsTable,
			Columns: []string{artist.AlbumsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlbumsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   artist.AlbumsTable,
			Columns: []string{artist.AlbumsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{artist.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ArtistUpdateOne is the builder for updating a single Artist entity.
type ArtistUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ArtistMutation
}

// SetName sets the "name" field.
func (_u *ArtistUpdateOne) SetName(v string) *ArtistUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ArtistUpdateOne) SetNillableName(v *string) *ArtistUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetImageURL sets the "image_url" field.
func (_u *ArtistUpdateOne) SetImageURL(v string) *ArtistUpdateOne {
	_u.mutation.SetImageURL(v)
	return _u
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_u *ArtistUpdateOne) SetNillableImageURL(v *string) *ArtistUpdateOne {
	if v != nil {
		_u.SetImageURL(*v)
	}
	return _u
}

// ClearImageURL clears the value of the "image_url" field.
func (_u *ArtistUpdateOne) ClearImageURL() *ArtistUpdateOne {
	_u.mutation.ClearImageURL()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *ArtistUpdateOne) SetCreatedAt(v time.Time) *ArtistUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *ArtistUpdateOne) SetNillableCreatedAt(v *time.Time) *ArtistUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddAlbumIDs adds the "albums" edge to the Album entity by IDs.
func (_u *ArtistUpdateOne) AddAlbumIDs(ids ...uuid.UUID) *ArtistUpdateOne {
	_u.mutation.AddAlbumIDs(ids...)
	return _u
}

// AddAlbums adds the "albums" edges to the Album entity.
func (_u *ArtistUpdateOne) AddAlbums(v ...*Album) *ArtistUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAlbumIDs(ids...)
}

// Mutation returns the ArtistMutation object of the builder.
func (_u *ArtistUpdateOne) Mutation() *ArtistMutation {
	return _u.mutation
}

// ClearAlbums clears all "albums" edges to the Album entity.
func (_u *ArtistUpdateOne) ClearAlbums() *ArtistUpdateOne {
	_u.mutation.ClearAlbums()
	return _u
}

// RemoveAlbumIDs removes the "albums" edge to Album entities by IDs.
func (_u *ArtistUpdateOne) RemoveAlbumIDs(ids ...uuid.UUID) *ArtistUpdateOne {
	_u.mutation.RemoveAlbumIDs(ids...)
	return _u
}

// RemoveAlbums removes "albums" edges to Album entities.
func (_u *ArtistUpdateOne) RemoveAlbums(v ...*Album) *ArtistUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAlbumIDs(ids...)
}

// Where appends a list predicates to the ArtistUpdate builder.
func (_u *ArtistUpdateOne) Where(ps ...predicate.Artist) *ArtistUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ArtistUpdateOne) Select(field string, fields ...string) *ArtistUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Artist entity.
func (_u *ArtistUpdateOne) Save(ctx context.Context) (*Artist, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ArtistUpdateOne) SaveX(ctx context.Context) *Artist {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ArtistUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ArtistUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ArtistUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := artist.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Artist.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ArtistUpdateOne) sqlSave(ctx context.Context) (_node *Artist, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(artist.Table, artist.Columns, sqlgraph.NewFieldSpec(artist.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Artist.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, artist.FieldID)
		for _, f := range fields {
			if !artist.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != artist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(artist.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ImageURL(); ok {
		_spec.SetField(artist.FieldImageURL, field.TypeString, value)
	}
	if _u.mutation.ImageURLCleared() {
		_spec.ClearField(artist.FieldImageURL, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(artist.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.AlbumsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   artist.AlbumsTable,
			Columns: []string{artist.AlbumsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAlbumsIDs(); len(nodes) > 0 && !_u.mutation.AlbumsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   artist.AlbumsTable,
			Columns: []string{artist.AlbumsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlbumsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   artist.AlbumsTable,
			Columns: []string{artist.AlbumsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Artist{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{artist.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
