// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"streamify/ent/album"
	"streamify/ent/predicate"
	"streamify/ent/track"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
)

// TrackUpdate is the builder for updating Track entities.
type TrackUpdate struct {
	config
	hooks    []Hook
	mutation *TrackMutation
}

// Where appends a list predicates to the TrackUpdate builder.
func (_u *TrackUpdate) Where(ps ...predicate.Track) *TrackUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *TrackUpdate) SetTitle(v string) *TrackUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TrackUpdate) SetNillableTitle(v *string) *TrackUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAlbumID sets the "album_id" field.
func (_u *TrackUpdate) SetAlbumID(v uuid.UUID) *TrackUpdate {
	_u.mutation.SetAlbumID(v)
	return _u
}

// SetNillableAlbumID sets the "album_id" field if the given value is not nil.
func (_u *TrackUpdate) SetNillableAlbumID(v *uuid.UUID) *TrackUpdate {
	if v != nil {
		_u.SetAlbumID(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *TrackUpdate) SetURL(v string) *TrackUpdate {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *TrackUpdate) SetNillableURL(v *string) *TrackUpdate {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *TrackUpdate) ClearURL() *TrackUpdate {
	_u.mutation.ClearURL()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TrackUpdate) SetCreatedAt(v time.Time) *TrackUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TrackUpdate) SetNillableCreatedAt(v *time.Time) *TrackUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetAlbum sets the "album" edge to the Album entity.
func (_u *TrackUpdate) SetAlbum(v *Album) *TrackUpdate {
	return _u.SetAlbumID(v.ID)
}

// Mutation returns the TrackMutation object of the builder.
func (_u *TrackUpdate) Mutation() *TrackMutation {
	return _u.mutation
}

// ClearAlbum clears the "album" edge to the Album entity.
func (_u *TrackUpdate) ClearAlbum() *TrackUpdate {
	_u.mutation.ClearAlbum()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TrackUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TrackUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TrackUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TrackUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TrackUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := track.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Track.title": %w`, err)}
		}
	}
	if _u.mutation.AlbumCleared() && len(_u.mutation.AlbumIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Track.album"`)
	}
	return nil
}

func (_u *TrackUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(track.Table, track.Columns, sqlgraph.NewFieldSpec(track.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(track.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(track.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(track.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(track.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.AlbumCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   track.AlbumTable,
			Columns: []string{track.AlbumColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlbumIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   track.AlbumTable,
			Columns: []string{track.AlbumColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{track.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TrackUpdateOne is the builder for updating a single Track entity.
type TrackUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TrackMutation
}

// SetTitle sets the "title" field.
func (_u *TrackUpdateOne) SetTitle(v string) *TrackUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *TrackUpdateOne) SetNillableTitle(v *string) *TrackUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetAlbumID sets the "album_id" field.
func (_u *TrackUpdateOne) SetAlbumID(v uuid.UUID) *TrackUpdateOne {
	_u.mutation.SetAlbumID(v)
	return _u
}

// SetNillableAlbumID sets the "album_id" field if the given value is not nil.
func (_u *TrackUpdateOne) SetNillableAlbumID(v *uuid.UUID) *TrackUpdateOne {
	if v != nil {
		_u.SetAlbumID(*v)
	}
	return _u
}

// SetURL sets the "url" field.
func (_u *TrackUpdateOne) SetURL(v string) *TrackUpdateOne {
	_u.mutation.SetURL(v)
	return _u
}

// SetNillableURL sets the "url" field if the given value is not nil.
func (_u *TrackUpdateOne) SetNillableURL(v *string) *TrackUpdateOne {
	if v != nil {
		_u.SetURL(*v)
	}
	return _u
}

// ClearURL clears the value of the "url" field.
func (_u *TrackUpdateOne) ClearURL() *TrackUpdateOne {
	_u.mutation.ClearURL()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *TrackUpdateOne) SetCreatedAt(v time.Time) *TrackUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *TrackUpdateOne) SetNillableCreatedAt(v *time.Time) *TrackUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetAlbum sets the "album" edge to the Album entity.
func (_u *TrackUpdateOne) SetAlbum(v *Album) *TrackUpdateOne {
	return _u.SetAlbumID(v.ID)
}

// Mutation returns the TrackMutation object of the builder.
func (_u *TrackUpdateOne) Mutation() *TrackMutation {
	return _u.mutation
}

// ClearAlbum clears the "album" edge to the Album entity.
func (_u *TrackUpdateOne) ClearAlbum() *TrackUpdateOne {
	_u.mutation.ClearAlbum()
	return _u
}

// Where appends a list predicates to the TrackUpdate builder.
func (_u *TrackUpdateOne) Where(ps ...predicate.Track) *TrackUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TrackUpdateOne) Select(field string, fields ...string) *TrackUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Track entity.
func (_u *TrackUpdateOne) Save(ctx context.Context) (*Track, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TrackUpdateOne) SaveX(ctx context.Context) *Track {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TrackUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TrackUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TrackUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := track.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "Track.title": %w`, err)}
		}
	}
	if _u.mutation.AlbumCleared() && len(_u.mutation.AlbumIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Track.album"`)
	}
	return nil
}

func (_u *TrackUpdateOne) sqlSave(ctx context.Context) (_node *Track, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(track.Table, track.Columns, sqlgraph.NewFieldSpec(track.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Track.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, track.FieldID)
		for _, f := range fields {
			if !track.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != track.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(track.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.URL(); ok {
		_spec.SetField(track.FieldURL, field.TypeString, value)
	}
	if _u.mutation.URLCleared() {
		_spec.ClearField(track.FieldURL, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(track.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.AlbumCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   track.AlbumTable,
			Columns: []string{track.AlbumColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AlbumIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   track.AlbumTable,
			Columns: []string{track.AlbumColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(album.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Track{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{track.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
