// Code generated by ent, DO NOT EDIT.

package ent

import (
	"streamify/ent/album"
	"streamify/ent/artist"
	"streamify/ent/schema"
	"streamify/ent/user"
	"time"

	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	albumFields := schema.Album{}.Fields()
	_ = albumFields
	// albumDescTitle is the schema descriptor for title field.
	albumDescTitle := albumFields[1].Descriptor()
	// album.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	album.TitleValidator = albumDescTitle.Validators[0].(func(string) error)
	// albumDescCreatedAt is the schema descriptor for created_at field.
	albumDescCreatedAt := albumFields[3].Descriptor()
	// album.DefaultCreatedAt holds the default value on creation for the created_at field.
	album.DefaultCreatedAt = albumDescCreatedAt.Default.(func() time.Time)
	// albumDescID is the schema descriptor for id field.
	albumDescID := albumFields[0].Descriptor()
	// album.DefaultID holds the default value on creation for the id field.
	album.DefaultID = albumDescID.Default.(func() uuid.UUID)
	artistFields := schema.Artist{}.Fields()
	_ = artistFields
	// artistDescName is the schema descriptor for name field.
	artistDescName := artistFields[1].Descriptor()
	// artist.NameValidator is a validator for the "name" field. It is called by the builders before save.
	artist.NameValidator = artistDescName.Validators[0].(func(string) error)
	// artistDescCreatedAt is the schema descriptor for created_at field.
	artistDescCreatedAt := artistFields[2].Descriptor()
	// artist.DefaultCreatedAt holds the default value on creation for the created_at field.
	artist.DefaultCreatedAt = artistDescCreatedAt.Default.(func() time.Time)
	// artistDescID is the schema descriptor for id field.
	artistDescID := artistFields[0].Descriptor()
	// artist.DefaultID holds the default value on creation for the id field.
	artist.DefaultID = artistDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = userDescEmail.Validators[0].(func(string) error)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
