# Schema reference: https://github.com/openintent/oiml/blob/main/packages/schema/project/index.ts
name: bacefook
description: "The best social media platform ever."
version: 0.1.0
api:
  framework: next
  language: typescript
database:
  type: postgres
  framework: prisma
  schema: prisma/schema.prisma
  connection: env:DATABASE_URL
  autorun_migrations: true
ui:
  framework: next
  language: typescript
paths:
  api: app/api
  components: app/components
  database: prisma/*
  types: packages/types
  tests: tests
intents:
  directory: .oiml/intents
